global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'disease-zone-app'
    static_configs:
      - targets: ['disease-zone-app:3000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'blockchain-api'
    static_configs:
      - targets: ['blockchain-api:4000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s